[build]
command = "pip install -r requirements.txt"
publish = "."
functions = "."

[build.environment]
PYTHON_VERSION = "3.9"  # Use your Python version

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
