"""experience changed to text

Revision ID: 12523a4ae889
Revises: 5ca3c5d75957
Create Date: 2025-04-05 16:38:31.966778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12523a4ae889'
down_revision = '5ca3c5d75957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty_staff', schema=None) as batch_op:
        batch_op.alter_column('experience',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty_staff', schema=None) as batch_op:
        batch_op.alter_column('experience',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
