"""pub year added column

Revision ID: 5ca3c5d75957
Revises: 84e2e0b05347
Create Date: 2025-03-29 15:33:47.008823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca3c5d75957'
down_revision = '84e2e0b05347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pub_year', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('pub_year')

    # ### end Alembic commands ###
