"""faculty_staff department added

Revision ID: 61687d5ad1d8
Revises: 12523a4ae889
Create Date: 2025-04-05 20:11:17.239307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61687d5ad1d8'
down_revision = '12523a4ae889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty_staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('d_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('faculty_staff_b_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'department', ['d_id'], ['d_id'], ondelete='CASCADE')
        batch_op.drop_column('b_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty_staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('b_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('faculty_staff_b_id_fkey', 'branch', ['b_id'], ['b_id'], ondelete='CASCADE')
        batch_op.drop_column('d_id')

    # ### end Alembic commands ###
