"""Reinitialized migrations

Revision ID: ef753e5329d8
Revises: 
Create Date: 2025-02-22 20:42:20.339173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef753e5329d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    op.drop_table('media')
    op.drop_table('department')
    op.drop_table('faculty_staff')
    op.drop_table('media_video_card')
    op.drop_table('social_media')
    op.drop_table('media_doc_card')
    op.drop_table('person')
    op.drop_table('student')
    op.drop_table('media_image_card')
    op.drop_table('alumni')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni',
    sa.Column('s_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('curr_org', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('brief', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['s_id'], ['student.s_id'], name='alumni_s_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('s_id', name='alumni_pkey')
    )
    op.create_table('media_image_card',
    sa.Column('media_img_id', sa.INTEGER(), server_default=sa.text("nextval('media_image_card_media_img_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('image_file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('image_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('media_img_id', name='media_image_card_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('student',
    sa.Column('s_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('p_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('join_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('media_img_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('d_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['d_id'], ['department.d_id'], name='student_d_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_img_id'], ['media_image_card.media_img_id'], name='student_media_img_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['p_id'], ['person.p_id'], name='student_p_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('s_id', name='student_pkey'),
    sa.UniqueConstraint('p_id', name='student_p_id_key')
    )
    op.create_table('person',
    sa.Column('p_id', sa.INTEGER(), server_default=sa.text("nextval('person_p_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email_pri', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email_sec', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone_no', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('alt_phone_no', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('curr_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('perm_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sm_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sm_id'], ['social_media.sm_id'], name='person_sm_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('p_id', name='person_pkey'),
    sa.UniqueConstraint('email_pri', name='person_email_pri_key'),
    sa.UniqueConstraint('sm_id', name='person_sm_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('media_doc_card',
    sa.Column('media_doc_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doc_file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('doc_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('media_doc_id', name='media_doc_card_pkey')
    )
    op.create_table('social_media',
    sa.Column('sm_id', sa.INTEGER(), server_default=sa.text("nextval('social_media_sm_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('insta', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('twitter', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('linkedin', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('youtube', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('sm_id', name='social_media_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('media_video_card',
    sa.Column('media_vid_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('video_file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('video_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('media_vid_id', name='media_video_card_pkey')
    )
    op.create_table('faculty_staff',
    sa.Column('f_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('p_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('join_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('media_img_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('d_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('positions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('f_or_s', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.CheckConstraint("f_or_s::text = ANY (ARRAY['Faculty'::character varying, 'Staff'::character varying]::text[])", name='faculty_staff_f_or_s_check'),
    sa.ForeignKeyConstraint(['d_id'], ['department.d_id'], name='faculty_staff_d_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_img_id'], ['media_image_card.media_img_id'], name='faculty_staff_media_img_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['p_id'], ['person.p_id'], name='faculty_staff_p_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('f_id', name='faculty_staff_pkey'),
    sa.UniqueConstraint('p_id', name='faculty_staff_p_id_key')
    )
    op.create_table('department',
    sa.Column('d_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dept_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('branch_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('d_id', name='department_pkey')
    )
    op.create_table('media',
    sa.Column('m_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('m_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('m_sub_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('added_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('added_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['person.p_id'], name='media_added_by_fkey'),
    sa.ForeignKeyConstraint(['updated_by'], ['person.p_id'], name='media_updated_by_fkey'),
    sa.PrimaryKeyConstraint('m_id', name='media_pkey')
    )
    op.create_table('card',
    sa.Column('c_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('c_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('c_sub_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('caption', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('added_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('added_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['person.p_id'], name='card_added_by_fkey'),
    sa.ForeignKeyConstraint(['updated_by'], ['person.p_id'], name='card_updated_by_fkey'),
    sa.PrimaryKeyConstraint('c_id', name='card_pkey')
    )
    # ### end Alembic commands ###
